/* global $ */

var tower = [
  {name: "bxlur", weight: 38},
  {name: "vgeifn", weight: 90},
  {name: "ehsqyyb", weight: 174,
    children: ["xtcdt", "tujcuy", "wiqohmb", "cxdwmu"]},
  {name: "xeqle", weight: 55},
  {name: "rvycd", weight: 1905,
    children: ["hspnsfg", "fyvlf", "lgkbca"]},
  {name: "lvohqo", weight: 41},
  {name: "vbiwa", weight: 88},
  {name: "jwvkdyy", weight: 25,
    children: ["eblot", "chpvnf", "uoasog", "upilubg"]},
  {name: "ymednx", weight: 75},
  {name: "snqeb", weight: 24},
  {name: "rrnhzu", weight: 72},
  {name: "arouyz", weight: 59},
  {name: "bgkxjiw", weight: 75},
  {name: "jhxdgxv", weight: 7},
  {name: "atkes", weight: 219,
    children: ["cbwagy", "dtzjt"]},
  {name: "zqicjh", weight: 86},
  {name: "rurhdvo", weight: 19},
  {name: "aijgw", weight: 5,
    children: ["ikegi", "gafbnc"]},
  {name: "aymrru", weight: 41},
  {name: "vmreal", weight: 6560,
    children: ["fpqpaes", "fjxvx", "nyrjj"]},
  {name: "qdqkaw", weight: 2229,
    children: ["hyukvw", "oahdsnf", "qizgiau"]},
  {name: "xhibern", weight: 90},
  {name: "tzclfir", weight: 8},
  {name: "eyumraw", weight: 99},
  {name: "datez", weight: 58},
  {name: "ddbixap", weight: 88},
  {name: "ipvdfc", weight: 84},
  {name: "hycmwzu", weight: 89},
  {name: "gjfmlc", weight: 263,
    children: ["gyehzo", "qflfg"]},
  {name: "cbrfntx", weight: 21},
  {name: "xpjgixx", weight: 58},
  {name: "wonqggh", weight: 7},
  {name: "rsjswd", weight: 199,
    children: ["lrqffb", "lvgrf"]},
  {name: "fihqkla", weight: 7},
  {name: "mdubrq", weight: 69},
  {name: "kjjuo", weight: 8},
  {name: "xgefj", weight: 81},
  {name: "yjuzr", weight: 45},
  {name: "jxqmtj", weight: 62,
    children: ["ryahia", "cidce", "vkdslcc", "kdnrfhs", "agyir", "bukih", "cdmidbh"]},
  {name: "rrqud", weight: 63},
  {name: "gykhcku", weight: 31,
    children: ["tthspe", "ohxvh"]},
  {name: "ikmldw", weight: 97,
    children: ["hjjchx", "ecbgp"]},
  {name: "gqauurp", weight: 79},
  {name: "xzmax", weight: 49},
  {name: "pvtmulz", weight: 5},
  {name: "hwgbp", weight: 34},
  {name: "imafbhs", weight: 8},
  {name: "qfxeio", weight: 21},
  {name: "xtvqhc", weight: 10},
  {name: "gybqyo", weight: 214,
    children: ["azdtrv", "oiyow"]},
  {name: "dqtls", weight: 5},
  {name: "pxxvg", weight: 63},
  {name: "aulkaf", weight: 42},
  {name: "xkdjnv", weight: 1697,
    children: ["kwenr", "sszjzj", "ierxej"]},
  {name: "maokm", weight: 1440,
    children: ["hrixd", "ixxaaz", "cewfc"]},
  {name: "jably", weight: 202,
    children: ["tfxzu", "ntnjsb", "ueoyysn", "qrmbao"]},
  {name: "pxijthu", weight: 72},
  {name: "nfebqt", weight: 61},
  {name: "ywvxjtz", weight: 76},
  {name: "ylwwnxo", weight: 79},
  {name: "raqfhc", weight: 21},
  {name: "pzpwzpp", weight: 61},
  {name: "ctcykka", weight: 7},
  {name: "zxrpdab", weight: 185,
    children: ["rjzmzv", "spfma"]},
  {name: "fhmeku", weight: 190,
    children: ["jvjim", "dgwfi"]},
  {name: "brwizly", weight: 150,
    children: ["feogbnr", "nygkcd", "pfolrs"]},
  {name: "zssrg", weight: 8},
  {name: "kfmkk", weight: 74},
  {name: "blcjl", weight: 61},
  {name: "fdtzsv", weight: 21},
  {name: "lxqing", weight: 71},
  {name: "vdxxgsn", weight: 51},
  {name: "tytnilq", weight: 6,
    children: ["avgmu", "ipvdfc", "cgyxd"]},
  {name: "nwipkns", weight: 76},
  {name: "klnuy", weight: 83,
    children: ["sbcry", "glcrysh"]},
  {name: "cdadt", weight: 37},
  {name: "bjjxgjb", weight: 88},
  {name: "nyrjj", weight: 308,
    children: ["mcmxown", "xogbq", "cdlqgyh", "cdcwgnc", "iiwvkl"]},
  {name: "cfcqxkp", weight: 231,
    children: ["zssrg", "uicmcph", "xhjfj", "qsdjow"]},
  {name: "uevmjdz", weight: 1776,
    children: ["koqxg", "knhfwbt", "yoyvf"]},
  {name: "ztnsgk", weight: 76},
  {name: "zfasn", weight: 48},
  {name: "pwabsd", weight: 76},
  {name: "yrmop", weight: 210,
    children: ["zmvsw", "skvukpc"]},
  {name: "warhhhp", weight: 75},
  {name: "caylbg", weight: 31},
  {name: "gdnzlar", weight: 49},
  {name: "jzmhc", weight: 41,
    children: ["ngftkym", "idksgg", "kfmkk"]},
  {name: "xsodot", weight: 254,
    children: ["voiho", "gjnnotg"]},
  {name: "xcllyx", weight: 86,
    children: ["pctuggx", "xpjgixx"]},
  {name: "cxocay", weight: 90},
  {name: "hutkx", weight: 33},
  {name: "qnknn", weight: 23},
  {name: "ftaxy", weight: 51,
    children: ["lkjbvw", "gexwzw", "cqoca", "xezjpye", "ftquc", "gggibf", "ferhk"]},
  {name: "tptuqv", weight: 812,
    children: ["qgofl", "encsf", "fevzwrt"]},
  {name: "vpuqhsd", weight: 32},
  {name: "cyetn", weight: 86,
    children: ["mnezur", "nvmkhp"]},
  {name: "dsdvxuw", weight: 49},
  {name: "wwdvt", weight: 95},
  {name: "tetsf", weight: 17},
  {name: "oilpcq", weight: 38},
  {name: "kampbl", weight: 65},
  {name: "zuimm", weight: 41},
  {name: "yjpmbe", weight: 80},
  {name: "rnkrh", weight: 25},
  {name: "ufknphd", weight: 26},
  {name: "rigjtc", weight: 55},
  {name: "rihloeh", weight: 2556,
    children: ["zyghjdm", "ydnxkn", "uzaousy"]},
  {name: "upilubg", weight: 75},
  {name: "madhzgb", weight: 17},
  {name: "uisdgr", weight: 57},
  {name: "xtgrt", weight: 33},
  {name: "lwcbxxt", weight: 19,
    children: ["claeea", "abjmnp"]},
  {name: "ipgoewc", weight: 58},
  {name: "jwioxco", weight: 789,
    children: ["yaezieu", "ofrehpy", "lgaruuy"]},
  {name: "lmvbhm", weight: 64},
  {name: "qtdha", weight: 85},
  {name: "jvjim", weight: 47},
  {name: "iszzan", weight: 8},
  {name: "ukdtleu", weight: 50,
    children: ["wmhucb", "cxbjh", "khfpks", "lgmfk"]},
  {name: "jznwy", weight: 56,
    children: ["ufnve", "adrate", "ynrpdhv", "szyya", "uacotzj", "keleq"]},
  {name: "fgctru", weight: 72,
    children: ["ydxbbv", "dssoru"]},
  {name: "amydoj", weight: 87,
    children: ["jqmzy", "jkjtbt", "xysxg"]},
  {name: "czvjqk", weight: 53,
    children: ["azsvcju", "gpvyac", "hygnrpp"]},
  {name: "ohxvh", weight: 34},
  {name: "gbiqrgk", weight: 169,
    children: ["orsmk", "owagdf"]},
  {name: "urgiwa", weight: 19},
  {name: "tmzut", weight: 80},
  {name: "yeovck", weight: 4685,
    children: ["efrqc", "uhvca", "cpajvuw", "emucaaw"]},
  {name: "jybhrc", weight: 275,
    children: ["srxvc", "xbopb"]},
  {name: "xjddt", weight: 5},
  {name: "karmp", weight: 29,
    children: ["rfjga", "qjdum", "nzojiy", "ysuoctn"]},
  {name: "fkemma", weight: 64,
    children: ["jghceu", "pvwdc"]},
  {name: "dzmsn", weight: 42},
  {name: "bxtzlhx", weight: 88},
  {name: "womays", weight: 310},
  {name: "lxukyz", weight: 18},
  {name: "kylpez", weight: 95,
    children: ["jtnoixl", "otozhke", "ucadng"]},
  {name: "amdcb", weight: 45},
  {name: "oubxwbc", weight: 44},
  {name: "wtksb", weight: 125,
    children: ["xyoenl", "prewuzd"]},
  {name: "vlwhjq", weight: 325},
  {name: "hpoawju", weight: 8},
  {name: "bqypkb", weight: 49},
  {name: "jwqnma", weight: 34},
  {name: "gvfit", weight: 33,
    children: ["mwybm", "pzyax"]},
  {name: "meonp", weight: 43},
  {name: "cxbjh", weight: 72},
  {name: "fuzizpc", weight: 68},
  {name: "pvzri", weight: 141,
    children: ["gzvnmz", "rexbt"]},
  {name: "lqtckpk", weight: 40},
  {name: "oiyow", weight: 20},
  {name: "cpajvuw", weight: 95,
    children: ["qdygxw", "pduav", "bpopmlv", "stwrufp"]},
  {name: "txkyw", weight: 85},
  {name: "juukhpw", weight: 42,
    children: ["ltpprm", "dchgfut"]},
  {name: "rmqhdxq", weight: 31},
  {name: "jymsax", weight: 70,
    children: ["vtzpyp", "ybsetv", "eagtrv"]},
  {name: "uhguep", weight: 98},
  {name: "eagtrv", weight: 55},
  {name: "sfwbytd", weight: 1939,
    children: ["fkemma", "yrahjwp", "qgiwga"]},
  {name: "occdw", weight: 108,
    children: ["frqzl", "lpbhq"]},
  {name: "sypqjit", weight: 37},
  {name: "axarhk", weight: 16,
    children: ["cbysja", "kglxzv", "nhrymw", "huantpz", "szeii", "cigtx", "ensfvaq"]},
  {name: "fyvlf", weight: 88,
    children: ["hhsge", "jbmclpv"]},
  {name: "qqxng", weight: 19},
  {name: "hvtqmrn", weight: 44},
  {name: "mrmebqc", weight: 37},
  {name: "azdtrv", weight: 20},
  {name: "iusyvt", weight: 29},
  {name: "rsebxf", weight: 53},
  {name: "uoasog", weight: 75},
  {name: "ivflnax", weight: 7},
  {name: "hktqef", weight: 136,
    children: ["tslksz", "tamkjw"]},
  {name: "iowcjno", weight: 56,
    children: ["qzwkx", "temdg"]},
  {name: "gfzqihm", weight: 195,
    children: ["whurga", "cihne"]},
  {name: "lcgdtru", weight: 49},
  {name: "qceysy", weight: 23},
  {name: "hjqlg", weight: 15},
  {name: "fxgehjm", weight: 149,
    children: ["imafbhs", "kjjuo", "tzclfir"]},
  {name: "oaiybyl", weight: 30},
  {name: "nsenvi", weight: 72},
  {name: "tkhlk", weight: 371,
    children: ["rlxnjv", "jvyfuqy"]},
  {name: "wiumq", weight: 10},
  {name: "xqrgxx", weight: 3249,
    children: ["oqrht", "uevmjdz", "lyvwjt"]},
  {name: "szeii", weight: 230,
    children: ["ntftdmt", "cjvxdq"]},
  {name: "bucnil", weight: 25,
    children: ["mlneyln", "gdndd", "tvooztp", "lpycpao"]},
  {name: "rvbrodj", weight: 49},
  {name: "lxxfs", weight: 16640,
    children: ["vxgsa", "eicae", "pkgqybo"]},
  {name: "uxunlz", weight: 25},
  {name: "trvqvd", weight: 81,
    children: ["iwuvvl", "ludvj", "yiqqluf", "muiela", "yrmop", "pwxllbx"]},
  {name: "pclpjq", weight: 21,
    children: ["omoin", "aifwngi"]},
  {name: "oatryy", weight: 1767,
    children: ["taljv", "qxylp", "hqyhx", "ahkztpf"]},
  {name: "xtcdt", weight: 26},
  {name: "wbaldd", weight: 13},
  {name: "sqenog", weight: 22,
    children: ["dhnttwg", "exryas", "rrnhzu"]},
  {name: "hwdfkq", weight: 15},
  {name: "tihsmo", weight: 81},
  {name: "swhwwgj", weight: 37},
  {name: "eunqr", weight: 31},
  {name: "erxep", weight: 66},
  {name: "edzfey", weight: 84},
  {name: "nbutjk", weight: 36},
  {name: "ymfatu", weight: 59},
  {name: "prucq", weight: 12},
  {name: "oopwi", weight: 18},
  {name: "xzhus", weight: 76},
  {name: "sbvgp", weight: 281,
    children: ["treywsr", "ahvzxw"]},
  {name: "spcwbv", weight: 54},
  {name: "otont", weight: 24,
    children: ["bilbca", "okard"]},
  {name: "ymexya", weight: 85},
  {name: "rrfjfe", weight: 9},
  {name: "dxonm", weight: 46},
  {name: "fnedd", weight: 49,
    children: ["ddbixap", "bxtzlhx"]},
  {name: "deuwm", weight: 277},
  {name: "mluyp", weight: 57},
  {name: "ialxayo", weight: 17},
  {name: "zmekfc", weight: 17},
  {name: "sltfq", weight: 135,
    children: ["nofof", "xzfbr"]},
  {name: "vhyyv", weight: 54},
  {name: "hbjhi", weight: 20},
  {name: "kfjztke", weight: 28},
  {name: "srkft", weight: 650,
    children: ["wixxqy", "aajfrf", "enlcjc", "bfkcjn"]},
  {name: "sjqnci", weight: 50,
    children: ["rvycd", "oatryy", "tjqcdi", "fantkyj", "gastvq", "tildgc", "wvwqp"]},
  {name: "aprln", weight: 53},
  {name: "qweyg", weight: 82},
  {name: "nbidkx", weight: 82},
  {name: "xjmhhb", weight: 3669,
    children: ["kmtyyw", "foghvqs", "ruadem"]},
  {name: "eqdoyk", weight: 89},
  {name: "dchgfut", weight: 90},
  {name: "anzjm", weight: 34},
  {name: "drvhp", weight: 117,
    children: ["jxwvdj", "ymfatu"]},
  {name: "qxwiktp", weight: 77},
  {name: "vvfrqo", weight: 33},
  {name: "jmcvwof", weight: 54},
  {name: "yylhcwe", weight: 4583,
    children: ["jxqmtj", "eesynky", "wsuetci", "rihloeh"]},
  {name: "wlxkzyu", weight: 69,
    children: ["ekild", "kuiik"]},
  {name: "earhrts", weight: 28,
    children: ["yeqsa", "pzbruav", "nqobvf"]},
  {name: "cyxdrb", weight: 42},
  {name: "kilai", weight: 70,
    children: ["phbyft", "cdurt"]},
  {name: "teekb", weight: 2069,
    children: ["lzwvg", "wfdxzo", "sjaimla"]},
  {name: "kyrfsv", weight: 22},
  {name: "luzyhbe", weight: 252,
    children: ["rijys", "ktwba"]},
  {name: "jwytokt", weight: 20},
  {name: "yalvg", weight: 41},
  {name: "ivejr", weight: 78},
  {name: "isdcga", weight: 90,
    children: ["fltpoim", "colszxn"]},
  {name: "jvyfuqy", weight: 13},
  {name: "nyfzqsd", weight: 93},
  {name: "fwqle", weight: 324,
    children: ["hwgbp", "anzjm", "jwqnma"]},
  {name: "ogfsdjs", weight: 132,
    children: ["bjctm", "kbapj"]},
  {name: "watbsp", weight: 86},
  {name: "koviipt", weight: 5},
  {name: "jeeyjk", weight: 89},
  {name: "vxlbjn", weight: 37},
  {name: "uaojqj", weight: 36},
  {name: "ebargy", weight: 93},
  {name: "ojqkqas", weight: 105,
    children: ["lmmde", "xzhus", "joohyti"]},
  {name: "zxsoo", weight: 126,
    children: ["fzmhn", "pvzhrs"]},
  {name: "nygkcd", weight: 25},
  {name: "elqusuf", weight: 7},
  {name: "ppkmo", weight: 49,
    children: ["jwdtam", "raqadrs"]},
  {name: "muahqz", weight: 65},
  {name: "qrmbao", weight: 13},
  {name: "dhilxlz", weight: 85},
  {name: "yexjxnd", weight: 74,
    children: ["nlnqo", "irvuv"]},
  {name: "pvzhrs", weight: 66},
  {name: "qsdjow", weight: 8},
  {name: "phbyft", weight: 55},
  {name: "yixjhrx", weight: 27},
  {name: "foghvqs", weight: 79,
    children: ["vlwhjq", "jwvkdyy", "juflvu", "hvwtr", "kicca", "dzlygu"]},
  {name: "iilaoq", weight: 7},
  {name: "qnwlb", weight: 45,
    children: ["rqxgeqm", "iqtij", "ypqsdaa", "nsenvi"]},
  {name: "hxexq", weight: 79},
  {name: "wksouwn", weight: 241,
    children: ["dbuzcp", "lhclwhi"]},
  {name: "lpbbxoq", weight: 86},
  {name: "lnpla", weight: 97,
    children: ["zocuuld", "zuvar", "zxsxos", "awmjc"]},
  {name: "smmjrpi", weight: 38},
  {name: "fqjhd", weight: 83},
  {name: "tujcuy", weight: 26},
  {name: "rfjga", weight: 88},
  {name: "npjyxjn", weight: 39},
  {name: "eayxrho", weight: 559,
    children: ["ymqaag", "ninnxgi", "yexjxnd", "zwrifke", "tytnilq", "zxsoo", "euask"]},
  {name: "wfvumx", weight: 31},
  {name: "ekdrgm", weight: 76},
  {name: "sbcry", weight: 78},
  {name: "durycn", weight: 53,
    children: ["nifzp", "jhhnkho", "jlzlxib", "cqhgy"]},
  {name: "otxmmd", weight: 235},
  {name: "bpmqk", weight: 80},
  {name: "eicae", weight: 121,
    children: ["rddasm", "xhibern"]},
  {name: "zcvtef", weight: 72},
  {name: "nsoes", weight: 37},
  {name: "dsmuem", weight: 31},
  {name: "jwvgc", weight: 89},
  {name: "sgabt", weight: 9},
  {name: "deoiu", weight: 23},
  {name: "arqruaa", weight: 76},
  {name: "ryqaxd", weight: 23},
  {name: "mlhqqjt", weight: 15},
  {name: "nndiv", weight: 153,
    children: ["wmqzq", "wgqus"]},
  {name: "tthspe", weight: 34},
  {name: "ahgtamk", weight: 58},
  {name: "unwpat", weight: 75},
  {name: "lyhuihb", weight: 8},
  {name: "jejhp", weight: 329,
    children: ["hbpbcf", "dafryf", "ojwprv"]},
  {name: "vqomvt", weight: 4087,
    children: ["wknjhvo", "mrexh", "fjjgfl", "rfldln"]},
  {name: "kwvkbv", weight: 35},
  {name: "tyati", weight: 38},
  {name: "hspnsfg", weight: 164,
    children: ["pzgagh", "madhzgb"]},
  {name: "ujpjxn", weight: 54},
  {name: "opwmti", weight: 95},
  {name: "swwwls", weight: 226},
  {name: "gwhqhzb", weight: 54},
  {name: "krbtc", weight: 54},
  {name: "txqrl", weight: 60},
  {name: "yrucl", weight: 349,
    children: ["qfxeio", "mkrkkri", "kimkb", "rllniuw"]},
  {name: "kumyda", weight: 328,
    children: ["azkwjyi", "cyfuqq", "tydgx"]},
  {name: "ljlbpd", weight: 91},
  {name: "fzmhn", weight: 66},
  {name: "yjvyqo", weight: 295,
    children: ["gnirnf", "tflkhk", "dyfioe"]},
  {name: "jyvgy", weight: 93,
    children: ["uhguep", "idpng"]},
  {name: "zlrwizb", weight: 66},
  {name: "nhrymw", weight: 85,
    children: ["slvygt", "lqhud", "putleq"]},
  {name: "goaeny", weight: 60,
    children: ["wwdvt", "gbuxs", "oacpgj", "opwmti"]},
  {name: "palczfm", weight: 92},
  {name: "elwic", weight: 60},
  {name: "inqto", weight: 55},
  {name: "gpvyac", weight: 64},
  {name: "ebtazb", weight: 312,
    children: ["hpoawju", "cidfe", "iszzan", "qimhnpk"]},
  {name: "pawxyqe", weight: 42},
  {name: "piigjh", weight: 80},
  {name: "tyviul", weight: 199,
    children: ["tgedm", "unxjpl"]},
  {name: "sazkwox", weight: 76},
  {name: "kvrmjma", weight: 9},
  {name: "qgofl", weight: 84,
    children: ["dugorw", "srybbkw"]},
  {name: "pegrxl", weight: 13},
  {name: "mzxyyfo", weight: 20},
  {name: "onpzd", weight: 26},
  {name: "pdumcu", weight: 94},
  {name: "yxdkhlx", weight: 23,
    children: ["izgqj", "smmjrpi"]},
  {name: "cxdwmu", weight: 26},
  {name: "ypqsdaa", weight: 72},
  {name: "nzojiy", weight: 88},
  {name: "xyoenl", weight: 50},
  {name: "avgmu", weight: 84},
  {name: "yqrjk", weight: 2271,
    children: ["ovdsrbq", "rgnjr"]},
  {name: "ivfbcy", weight: 40},
  {name: "knhfwbt", weight: 131},
  {name: "fxdfhtc", weight: 24},
  {name: "vwepws", weight: 69,
    children: ["mluyp", "unfrsh"]},
  {name: "qxdfu", weight: 5},
  {name: "mwuhto", weight: 85,
    children: ["aisrfn", "piigjh"]},
  {name: "wymbxxi", weight: 186,
    children: ["amfdzum", "otont", "xcllyx", "iowcjno"]},
  {name: "gdzcx", weight: 68},
  {name: "mqtmr", weight: 40},
  {name: "kwavxzh", weight: 39},
  {name: "anpyn", weight: 22},
  {name: "rnrxeb", weight: 80},
  {name: "dzlrn", weight: 51,
    children: ["kcqshd", "rmqhdxq", "caylbg"]},
  {name: "vbutj", weight: 14},
  {name: "edguzhg", weight: 6},
  {name: "wlffbug", weight: 65,
    children: ["qavye", "anpyn"]},
  {name: "qimhnpk", weight: 8},
  {name: "uhottvw", weight: 36,
    children: ["ymexya", "ezespi", "mjeni"]},
  {name: "pcfilur", weight: 52242,
    children: ["yeovck", "vmreal", "cqqmsv"]},
  {name: "vfkzaix", weight: 193,
    children: ["pegrxl", "wbaldd"]},
  {name: "ecbgp", weight: 58},
  {name: "vkugys", weight: 36},
  {name: "kmiubc", weight: 249,
    children: ["sqenog", "jchpv", "bryzg", "owzsiku", "coiuo", "hbvroo"]},
  {name: "yokbals", weight: 19},
  {name: "muivti", weight: 17},
  {name: "fzjuimt", weight: 12161,
    children: ["maokm", "ntvpob", "qyrope"]},
  {name: "jxwvdj", weight: 59},
  {name: "bswzafr", weight: 12,
    children: ["dlmmqrm", "hznqtl"]},
  {name: "mkbny", weight: 230,
    children: ["fmfksfr", "ocriw"]},
  {name: "azsurm", weight: 19},
  {name: "vkdslcc", weight: 360,
    children: ["ndvnqb", "pjrtq"]},
  {name: "jeabki", weight: 206,
    children: ["bkpzlxc", "rrqud"]},
  {name: "qflfg", weight: 18},
  {name: "lojah", weight: 51},
  {name: "voiho", weight: 23},
  {name: "mwybm", weight: 70},
  {name: "csrjic", weight: 58},
  {name: "wcdlx", weight: 84},
  {name: "bmjswlz", weight: 11},
  {name: "qxoljws", weight: 47},
  {name: "gbuxs", weight: 95},
  {name: "kbapj", weight: 47},
  {name: "niexbbc", weight: 72},
  {name: "qeebfg", weight: 270,
    children: ["aqrawj", "wjxqn", "prsysf", "ukdtleu"]},
  {name: "fjxvx", weight: 688,
    children: ["gphoz", "bmoed", "ookaq", "nxrhbhh", "dfezv"]},
  {name: "kimkb", weight: 21},
  {name: "unfrsh", weight: 57},
  {name: "ijwptaq", weight: 73},
  {name: "zocuuld", weight: 45},
  {name: "ddjoygw", weight: 75},
  {name: "lwdgty", weight: 222,
    children: ["ofexdqx", "xizhxs"]},
  {name: "bexoza", weight: 57,
    children: ["pzgqbxm", "warhhhp", "wzcmmr", "phxjq"]},
  {name: "uiqwd", weight: 89},
  {name: "pvmgp", weight: 114,
    children: ["byduope", "atkagyc", "ibbtm"]},
  {name: "ydxbbv", weight: 95},
  {name: "kicca", weight: 325},
  {name: "ptfuyxs", weight: 30},
  {name: "gyehzo", weight: 18},
  {name: "itnpmen", weight: 29},
  {name: "mjmjubw", weight: 79,
    children: ["hixroxf", "hmxzkwe"]},
  {name: "enlcjc", weight: 59},
  {name: "kwenr", weight: 79,
    children: ["ehajus", "pxxvg"]},
  {name: "lvbgz", weight: 62},
  {name: "vhauylt", weight: 58},
  {name: "eixgei", weight: 54},
  {name: "usuyhvw", weight: 76},
  {name: "pwxllbx", weight: 186,
    children: ["oaiybyl", "roquwk"]},
  {name: "hjgaun", weight: 40},
  {name: "ucadng", weight: 40},
  {name: "lpkak", weight: 207,
    children: ["azsurm", "kyxphrr"]},
  {name: "idpng", weight: 98},
  {name: "ddpqp", weight: 95},
  {name: "qxwmd", weight: 67},
  {name: "qeidnw", weight: 298,
    children: ["qvtxsu", "jjqpm"]},
  {name: "eivaq", weight: 75,
    children: ["utydsr", "swhwwgj"]},
  {name: "hrixd", weight: 31,
    children: ["keuzyp", "iusyvt", "perxaan"]},
  {name: "ejygwyb", weight: 932,
    children: ["txagu", "mbzah", "bcnwjsb", "eivaq", "bcicoat"]},
  {name: "ddhzzxi", weight: 23},
  {name: "kzjfx", weight: 42},
  {name: "qllpxw", weight: 19},
  {name: "hmxzkwe", weight: 51},
  {name: "fhayyvm", weight: 24},
  {name: "lvauv", weight: 42},
  {name: "woasw", weight: 88},
  {name: "cmpldn", weight: 75},
  {name: "ibxkkj", weight: 45},
  {name: "abvvbtl", weight: 48},
  {name: "idksgg", weight: 74},
  {name: "pmyvcx", weight: 64},
  {name: "sbeizwi", weight: 31},
  {name: "xsaqyd", weight: 49},
  {name: "fevzwrt", weight: 178,
    children: ["bruxjz", "zjbmj"]},
  {name: "cqqmsv", weight: 79,
    children: ["axnnyq", "pbmhfx", "teekb", "popwmey", "gomgkol"]},
  {name: "clwnxrx", weight: 39},
  {name: "ikegr", weight: 61},
  {name: "hsagb", weight: 87},
  {name: "jchpv", weight: 68,
    children: ["lrvwrl", "quaey"]},
  {name: "jauxs", weight: 180,
    children: ["xcubkli", "zuimm", "lvohqo", "mpkgky"]},
  {name: "midyfh", weight: 140,
    children: ["zkmtesi", "yalvg", "aymrru"]},
  {name: "msnicb", weight: 42},
  {name: "ahxnebz", weight: 18},
  {name: "skhjb", weight: 163,
    children: ["czllgn", "hwdfkq"]},
  {name: "ziyhyly", weight: 25,
    children: ["hizhauj", "niexbbc"]},
  {name: "jkjtbt", weight: 62},
  {name: "hjeeb", weight: 33},
  {name: "mdgqhkw", weight: 56},
  {name: "boblgpx", weight: 95},
  {name: "lvgrf", weight: 65},
  {name: "anbdqml", weight: 31},
  {name: "jrrgvqf", weight: 82,
    children: ["xsaqyd", "zcmud"]},
  {name: "otadvyl", weight: 60},
  {name: "dpiexx", weight: 13,
    children: ["edxsfa", "sfvfge", "womays"]},
  {name: "otvta", weight: 39},
  {name: "slttwe", weight: 60},
  {name: "byegnb", weight: 85},
  {name: "agbhqmu", weight: 38},
  {name: "fmtmlgd", weight: 64},
  {name: "sjaimla", weight: 95},
  {name: "ctpfl", weight: 132,
    children: ["xxlzsza", "ekdrgm"]},
  {name: "xbmbzn", weight: 29},
  {name: "cnrgfkq", weight: 11963,
    children: ["tptuqv", "lfjkju", "fkinwya"]},
  {name: "khfpks", weight: 72},
  {name: "emkuxtl", weight: 107,
    children: ["elsqz", "iymnx", "lxgjn", "oyjrsw", "sbvgp"]},
  {name: "zxalnm", weight: 49,
    children: ["gdzcx", "emrzoi"]},
  {name: "lzwvg", weight: 35,
    children: ["atcrc", "msutjz", "emhikp"]},
  {name: "kpyped", weight: 23},
  {name: "uytekqt", weight: 14},
  {name: "bzwof", weight: 397,
    children: ["uulxzg", "eswhpi"]},
  {name: "atcckfh", weight: 131,
    children: ["ujpjxn", "jmcvwof"]},
  {name: "nyojm", weight: 309,
    children: ["zwprtx", "myaklce", "nqnvc", "xjddt"]},
  {name: "lmdteh", weight: 61},
  {name: "jjukrje", weight: 7},
  {name: "wgcckll", weight: 19},
  {name: "ferhk", weight: 568,
    children: ["kjegcl", "dzlrn", "vdkjcp", "tefpuyj"]},
  {name: "kemkox", weight: 61},
  {name: "wkyhcm", weight: 72},
  {name: "gjkrkw", weight: 83},
  {name: "pvwdc", weight: 39},
  {name: "clgsp", weight: 33},
  {name: "qalkey", weight: 7},
  {name: "sewpop", weight: 245},
  {name: "wvihp", weight: 8},
  {name: "ragqe", weight: 10},
  {name: "qtfpf", weight: 5},
  {name: "hqvvtr", weight: 43},
  {name: "tiqmony", weight: 24},
  {name: "enuqt", weight: 94},
  {name: "uzxbp", weight: 24},
  {name: "hkorax", weight: 80},
  {name: "wocartl", weight: 67},
  {name: "cubeivy", weight: 49,
    children: ["iyywca", "pkafj", "nqmrbb"]},
  {name: "ylbprac", weight: 21},
  {name: "xrowfq", weight: 121,
    children: ["tyati", "agbhqmu", "ypetsiw"]},
  {name: "txwypo", weight: 59,
    children: ["npjyxjn", "uhpbxq", "otvta", "hoemev"]},
  {name: "nofof", weight: 82},
  {name: "vmwmulw", weight: 4725,
    children: ["lriegav", "ejygwyb", "kmiubc"]},
  {name: "shuqg", weight: 47},
  {name: "ampno", weight: 43},
  {name: "ndmej", weight: 73},
  {name: "gdndd", weight: 93},
  {name: "xvafyvk", weight: 13,
    children: ["clxdcd", "sxakrws", "afwufw", "fwqle", "ctaya"]},
  {name: "lqhud", weight: 81},
  {name: "byijdr", weight: 8,
    children: ["lpbbxoq", "zqicjh"]},
  {name: "vdjoaq", weight: 20},
  {name: "wjuyj", weight: 62},
  {name: "ugmwpnx", weight: 183},
  {name: "lshtqgp", weight: 80},
  {name: "tufamsz", weight: 37},
  {name: "piztdav", weight: 6},
  {name: "zcvlo", weight: 23,
    children: ["eyumraw", "hnulxpf"]},
  {name: "gzvnmz", weight: 16},
  {name: "wbmahc", weight: 80},
  {name: "ensfvaq", weight: 146,
    children: ["ljlbpd", "pkvblpt"]},
  {name: "iefpjj", weight: 76},
  {name: "jsjxl", weight: 78},
  {name: "sxfptlh", weight: 62},
  {name: "jwmtw", weight: 97,
    children: ["eoeiflq", "oilpcq"]},
  {name: "ojxixj", weight: 290,
    children: ["xtvqhc", "rvosgv"]},
  {name: "ylftgo", weight: 166,
    children: ["dxspx", "ctcykka"]},
  {name: "xsepgg", weight: 156,
    children: ["lcgdtru", "rvbrodj"]},
  {name: "yrwzi", weight: 288,
    children: ["wqqmvoe", "bxeum"]},
  {name: "efriw", weight: 135,
    children: ["uxunlz", "ejkioj"]},
  {name: "xlkuot", weight: 35},
  {name: "nhqgb", weight: 85},
  {name: "nxian", weight: 58},
  {name: "oscxinx", weight: 44},
  {name: "ncdbvaa", weight: 54},
  {name: "mfcryoc", weight: 57},
  {name: "cqoyqhn", weight: 85},
  {name: "slifb", weight: 40},
  {name: "rcelntk", weight: 66},
  {name: "axnnyq", weight: 1358,
    children: ["wpirdu", "jeabki", "yorypq"]},
  {name: "rhxhumv", weight: 67},
  {name: "jgxph", weight: 92},
  {name: "dalhs", weight: 108,
    children: ["nbutjk", "uaojqj"]},
  {name: "zmvsw", weight: 18},
  {name: "hkgcdih", weight: 763,
    children: ["ndprukh", "vgeifn"]},
  {name: "ntvpob", weight: 789,
    children: ["ouabu", "ucyuje", "enjrxrw"]},
  {name: "jdzlhqw", weight: 99},
  {name: "peqsua", weight: 153,
    children: ["zntwpqo", "nhale", "bjdfo", "wiumq"]},
  {name: "cpdapys", weight: 39},
  {name: "ysqronq", weight: 75},
  {name: "putleq", weight: 81},
  {name: "dyvgigf", weight: 41},
  {name: "xocsd", weight: 5},
  {name: "pipax", weight: 40,
    children: ["dzmsn", "ujmboh", "xcrvb", "lvauv"]},
  {name: "cqfebqe", weight: 52},
  {name: "fitaq", weight: 283,
    children: ["ajrle", "baqiy"]},
  {name: "lsmylfm", weight: 217,
    children: ["jdzlhqw", "lrsoyci"]},
  {name: "kukri", weight: 70},
  {name: "hqyhx", weight: 31,
    children: ["ztnsgk", "yzlzly"]},
  {name: "tydgx", weight: 102,
    children: ["synxk", "smcru"]},
  {name: "keuzyp", weight: 29},
  {name: "lpilno", weight: 122,
    children: ["hqvvtr", "bbenpz"]},
  {name: "wfdxzo", weight: 41,
    children: ["wbxcy", "bfbbi"]},
  {name: "azfrf", weight: 44},
  {name: "hdzls", weight: 58881,
    children: ["ayeric", "vqomvt", "huqgqdb", "scngxng"]},
  {name: "kdgummr", weight: 149,
    children: ["deoiu", "kvwjces", "mpnodas"]},
  {name: "nqnvc", weight: 5},
  {name: "cbysja", weight: 268,
    children: ["bzuiexp", "tsrob", "hbjhi"]},
  {name: "xiecr", weight: 20},
  {name: "cuajqvk", weight: 95},
  {name: "rwupp", weight: 8},
  {name: "qdygxw", weight: 268,
    children: ["ykxkahj", "kwavxzh", "vkpgf", "clwnxrx"]},
  {name: "dtzjt", weight: 89},
  {name: "urnlyx", weight: 5},
  {name: "emucaaw", weight: 13,
    children: ["jably", "xsepgg", "ywwovs", "cyetn", "clnzh", "gybqyo", "mdwrg"]},
  {name: "avugbx", weight: 8},
  {name: "zxtxfdm", weight: 882,
    children: ["jnvrw", "jyvgy", "gjpgk"]},
  {name: "pkgqybo", weight: 179,
    children: ["kemkox", "jzkkmio"]},
  {name: "hnulxpf", weight: 99},
  {name: "atkagyc", weight: 28},
  {name: "iukhsi", weight: 41,
    children: ["zcvtef", "bwiee"]},
  {name: "rgdsxy", weight: 12},
  {name: "uwwmhl", weight: 75},
  {name: "klgolly", weight: 19},
  {name: "ypetsiw", weight: 38},
  {name: "igoifku", weight: 241,
    children: ["njoqwl", "prucq"]},
  {name: "raqadrs", weight: 93},
  {name: "ejkfjsb", weight: 109},
  {name: "hbqxmkz", weight: 51},
  {name: "yaezieu", weight: 238,
    children: ["izqne", "rrfjfe"]},
  {name: "yblpan", weight: 70},
  {name: "kycvcdb", weight: 26},
  {name: "zazwgl", weight: 30},
  {name: "ayeric", weight: 2991,
    children: ["cwcmr", "mcwevy", "duyvc"]},
  {name: "cewfc", weight: 22,
    children: ["usudfnb", "zfasn"]},
  {name: "zfbolo", weight: 24},
  {name: "jcortpe", weight: 57},
  {name: "vdppt", weight: 74,
    children: ["awgqw", "qxdfu", "hkljrrq", "yhkof"]},
  {name: "ujtyd", weight: 62},
  {name: "cweqffl", weight: 16},
  {name: "dhpxdx", weight: 85,
    children: ["puvhodg", "cikitqj"]},
  {name: "jbqfn", weight: 84},
  {name: "colszxn", weight: 86},
  {name: "qxerd", weight: 152,
    children: ["cqhnl", "cnksi"]},
  {name: "scngxng", weight: 3999,
    children: ["jejhp", "chpcn", "ejwrem"]},
  {name: "keleq", weight: 141,
    children: ["otadvyl", "txqrl"]},
  {name: "iwuvvl", weight: 80,
    children: ["fqjhd", "gjkrkw"]},
  {name: "fvord", weight: 24},
  {name: "nyvjvra", weight: 49},
  {name: "vabwqou", weight: 68},
  {name: "byduope", weight: 28},
  {name: "lgkbca", weight: 141,
    children: ["klgolly", "yokbals", "mpamey"]},
  {name: "qogcdog", weight: 97},
  {name: "aqzibdb", weight: 65},
  {name: "ocriw", weight: 57},
  {name: "tnvtn", weight: 97},
  {name: "flgljqv", weight: 22},
  {name: "utyriu", weight: 62},
  {name: "flikvl", weight: 49},
  {name: "tplrfil", weight: 32},
  {name: "xiuxqpp", weight: 403,
    children: ["moqub", "ysexyc"]},
  {name: "ndpjdmr", weight: 87},
  {name: "ocsqis", weight: 14},
  {name: "rdzzlw", weight: 17,
    children: ["ikkxpuo", "kdjoii"]},
  {name: "avgsmcl", weight: 89},
  {name: "uhvca", weight: 603,
    children: ["hgnkw", "kxlbaue", "nnyzm", "cfcmep", "pvmgp", "dviuy"]},
  {name: "ymqaag", weight: 144,
    children: ["dzkqrjf", "yhfjs", "sunnnk"]},
  {name: "gadpuyh", weight: 85},
  {name: "pkaqx", weight: 1639,
    children: ["rigjtc", "inqto"]},
  {name: "bjctm", weight: 47},
  {name: "nqvntc", weight: 14885,
    children: ["eemyrwb", "srkft", "wvlri"]},
  {name: "kapmsr", weight: 54},
  {name: "txagu", weight: 51,
    children: ["nyvjvra", "flikvl"]},
  {name: "mxnvqf", weight: 43},
  {name: "orwwh", weight: 64},
  {name: "awwicqq", weight: 19},
  {name: "tzepblp", weight: 60},
  {name: "bmxdb", weight: 54},
  {name: "ayntidu", weight: 1251,
    children: ["dalhs", "jrrgvqf", "bikrg"]},
  {name: "sxakrws", weight: 426},
  {name: "zkpbt", weight: 97},
  {name: "zcmud", weight: 49},
  {name: "isvfqpy", weight: 33},
  {name: "ikegi", weight: 94},
  {name: "oxdqy", weight: 71},
  {name: "dtedfv", weight: 559,
    children: ["ortfml", "hktqef", "xbhhxq", "yheme", "lwdgty", "iftzv", "rcvhb"]},
  {name: "otozhke", weight: 40},
  {name: "wdanz", weight: 277,
    children: ["szejcb", "hudgw"]},
  {name: "xfnmqd", weight: 75,
    children: ["ggmgzhd", "krbtc"]},
  {name: "tpafkv", weight: 46,
    children: ["watbsp", "xuoags"]},
  {name: "rllniuw", weight: 21},
  {name: "ltpprm", weight: 90},
  {name: "kyxphrr", weight: 19},
  {name: "yhkof", weight: 5},
  {name: "ofexdqx", weight: 18},
  {name: "uqyqwny", weight: 58},
  {name: "yfxxnzi", weight: 221},
  {name: "lekky", weight: 97,
    children: ["xflldsr", "hgfxb", "nxian", "vhauylt"]},
  {name: "lriegav", weight: 32,
    children: ["tbimd", "nrvgs", "jymsax", "ppkmo", "oukjop", "drvhp", "xrowfq"]},
  {name: "qrlcg", weight: 80},
  {name: "hethruu", weight: 7},
  {name: "zwrifke", weight: 216,
    children: ["ylbprac", "yywuo"]},
  {name: "cjvxdq", weight: 49},
  {name: "ezespi", weight: 85},
  {name: "acfzx", weight: 10},
  {name: "lzuon", weight: 70},
  {name: "dnwlq", weight: 86,
    children: ["lugtnb", "vvfrqo", "gujrqf"]},
  {name: "gqejmuy", weight: 43},
  {name: "jcmbf", weight: 185},
  {name: "pohtiuv", weight: 47},
  {name: "chmmaa", weight: 221},
  {name: "tjqcdi", weight: 1759,
    children: ["okmrsd", "jcmbf", "iukhsi", "zxalnm"]},
  {name: "skvukpc", weight: 18},
  {name: "dwxem", weight: 80},
  {name: "dyfioe", weight: 5},
  {name: "bmoed", weight: 179,
    children: ["ahxnebz", "blqvp"]},
  {name: "eswhpi", weight: 9},
  {name: "mdsms", weight: 80},
  {name: "aifwngi", weight: 76},
  {name: "qhttqrn", weight: 71,
    children: ["hbqxmkz", "ldcdes"]},
  {name: "nrwrhsp", weight: 62,
    children: ["satjbta", "iycds", "lekky", "lccfqhm", "jybhrc", "zxrpdab", "ycxsmt"]},
  {name: "beesdrz", weight: 487,
    children: ["xhkbihe", "oxxyy", "ziyhyly"]},
  {name: "oukxnyz", weight: 77,
    children: ["jeeyjk", "avgsmcl", "izmwsib"]},
  {name: "oxxyy", weight: 51,
    children: ["arouyz", "qleml"]},
  {name: "zzufnfx", weight: 76},
  {name: "nhale", weight: 10},
  {name: "vrezr", weight: 80},
  {name: "gphoz", weight: 167,
    children: ["nlnwd", "hzcbok", "djfzb", "wbtniv"]},
  {name: "oihlb", weight: 339,
    children: ["wztqxw", "shuqg"]},
  {name: "uhpbxq", weight: 39},
  {name: "fpqpaes", weight: 17,
    children: ["yatllw", "uhottvw", "mqtksj", "jpzmpas", "aylev", "ueusbib"]},
  {name: "tsrob", weight: 20},
  {name: "ljedj", weight: 221},
  {name: "pkafj", weight: 20},
  {name: "pwzlax", weight: 273},
  {name: "ekzsv", weight: 201,
    children: ["umdid", "ehpmmve"]},
  {name: "bikrg", weight: 108,
    children: ["ayqsng", "zuytxxd", "rxoja", "oopwi"]},
  {name: "bryzg", weight: 218,
    children: ["dqtls", "xocsd", "urnlyx", "jscgykv"]},
  {name: "znitfpo", weight: 70,
    children: ["usuyhvw", "nshqf"]},
  {name: "hvwtr", weight: 249,
    children: ["wflwje", "lhkwv"]},
  {name: "bvjkr", weight: 176,
    children: ["vdxxgsn", "lojah"]},
  {name: "arvmgnd", weight: 54},
  {name: "mpnodas", weight: 23},
  {name: "ruxilvv", weight: 82,
    children: ["vfipmtl", "bjjxgjb"]},
  {name: "zvhjz", weight: 93},
  {name: "wjxqn", weight: 248,
    children: ["hgnqq", "amdcb"]},
  {name: "uhcrfl", weight: 21409,
    children: ["yyjweq", "fzzbt", "kaylk", "cnrgfkq"]},
  {name: "hgfxb", weight: 58},
  {name: "zuytxxd", weight: 18},
  {name: "ltpwxbx", weight: 2760,
    children: ["kcqlos", "wnsnr", "zxtxfdm", "pkaqx"]},
  {name: "qvdkqw", weight: 309,
    children: ["sxfptlh", "ujtyd"]},
  {name: "upksf", weight: 10,
    children: ["yfxxnzi", "ghpotnp", "ljedj", "gfzqihm", "gopynr", "waaostj", "cilkhan"]},
  {name: "eyqpybt", weight: 75},
  {name: "rvosgv", weight: 10},
  {name: "bfbbi", weight: 27},
  {name: "vkpgf", weight: 39},
  {name: "oghwfv", weight: 122,
    children: ["klfkq", "kemaenc", "wfvumx"]},
  {name: "lyvwjt", weight: 1269,
    children: ["wtksb", "fnedd", "brwizly", "jvmpgso"]},
  {name: "encsf", weight: 182,
    children: ["sbeizwi", "eunqr"]},
  {name: "zigchs", weight: 90},
  {name: "eihea", weight: 27,
    children: ["ndmej", "ijwptaq"]},
  {name: "nrneucv", weight: 5},
  {name: "wgxlaau", weight: 60},
  {name: "ctnzjui", weight: 267,
    children: ["cweqffl", "jyjyy"]},
  {name: "skhjuz", weight: 80},
  {name: "exvcki", weight: 55},
  {name: "xflldsr", weight: 58},
  {name: "hudgw", weight: 28},
  {name: "cnksi", weight: 53},
  {name: "njmxjzn", weight: 65},
  {name: "nnyzm", weight: 150,
    children: ["chozum", "fhayyvm"]},
  {name: "mqkaob", weight: 31},
  {name: "mpkgky", weight: 41},
  {name: "oqrht", weight: 76,
    children: ["appwc", "wksouwn", "auoba", "ctnzjui", "gjfmlc", "ekzsv", "sltfq"]},
  {name: "fvvrow", weight: 68},
  {name: "ontvyu", weight: 80},
  {name: "yorypq", weight: 236,
    children: ["tivuls", "nqgfa", "uzxbp", "fxdfhtc"]},
  {name: "iycds", weight: 315,
    children: ["ivflnax", "hnevf"]},
  {name: "ywwovs", weight: 102,
    children: ["nwipkns", "pwabsd"]},
  {name: "mlneyln", weight: 93},
  {name: "hrbmwq", weight: 22},
  {name: "pxora", weight: 55},
  {name: "azsvcju", weight: 64},
  {name: "flrpj", weight: 67},
  {name: "hyvfpe", weight: 99},
  {name: "wsuetci", weight: 2388,
    children: ["ctpfl", "fhmeku", "bstmzd"]},
  {name: "coegpi", weight: 97},
  {name: "gfnhg", weight: 45},
  {name: "hbpbcf", weight: 207,
    children: ["fdtzsv", "cekovn"]},
  {name: "xbopb", weight: 27},
  {name: "uacotzj", weight: 261},
  {name: "jrqht", weight: 42},
  {name: "fslbtk", weight: 57},
  {name: "xbhhxq", weight: 189,
    children: ["qceysy", "kcftmnv", "vkbpp"]},
  {name: "eblot", weight: 75},
  {name: "puvhodg", weight: 58},
  {name: "spfma", weight: 72},
  {name: "dfezv", weight: 201,
    children: ["fihqkla", "hethruu"]},
  {name: "bqxiezq", weight: 49},
  {name: "tildgc", weight: 1627,
    children: ["tpafkv", "xwpuhf", "vcqgruj", "kdgummr"]},
  {name: "dkhyk", weight: 19},
  {name: "snxzn", weight: 81},
  {name: "zmnaori", weight: 75},
  {name: "lhkwv", weight: 38},
  {name: "emrzoi", weight: 68},
  {name: "ysexyc", weight: 15},
  {name: "ueoyysn", weight: 13},
  {name: "rpdslp", weight: 18},
  {name: "jzzng", weight: 44},
  {name: "rzqdqj", weight: 80},
  {name: "pdfzwaz", weight: 37},
  {name: "dzjvx", weight: 53,
    children: ["bxvaxw", "lucdfi"]},
  {name: "nflgixa", weight: 21},
  {name: "myaklce", weight: 5},
  {name: "yyjweq", weight: 40,
    children: ["nrwrhsp", "eayxrho", "udyms", "dtedfv", "sfwbytd", "vmghntr", "yqrjk"]},
  {name: "bcnwjsb", weight: 107,
    children: ["nflgixa", "ygjhtt"]},
  {name: "cilkhan", weight: 167,
    children: ["pfchj", "yixjhrx"]},
  {name: "hjkfjle", weight: 11},
  {name: "cihne", weight: 13},
  {name: "fkinwya", weight: 1480,
    children: ["sdljelr", "vpuqhsd"]},
  {name: "kirybeg", weight: 44},
  {name: "jmhafl", weight: 70,
    children: ["fedjn", "sazkwox"]},
  {name: "ebjym", weight: 38},
  {name: "ofrehpy", weight: 91,
    children: ["exvcki", "xzawv", "pxora"]},
  {name: "jqmzy", weight: 62},
  {name: "gggibf", weight: 112,
    children: ["qhfpnc", "ruxilvv", "gklao", "qxerd"]},
  {name: "smcru", weight: 60},
  {name: "dqggh", weight: 433},
  {name: "lpbhq", weight: 99},
  {name: "xzbry", weight: 52},
  {name: "iczndtj", weight: 201,
    children: ["jncdjr", "edguzhg"]},
  {name: "mcmxown", weight: 120,
    children: ["ygnys", "hpxoxk", "uisdgr"]},
  {name: "cfegyp", weight: 27},
  {name: "ndvnqb", weight: 47},
  {name: "bnrgfa", weight: 5},
  {name: "bivovn", weight: 88,
    children: ["cuajqvk", "ddpqp"]},
  {name: "omiwktf", weight: 71},
  {name: "mkxbl", weight: 162,
    children: ["kjzvcr", "lnmmac"]},
  {name: "gujrqf", weight: 33},
  {name: "szejcb", weight: 28},
  {name: "tslksz", weight: 61},
  {name: "vsshf", weight: 67,
    children: ["sypqjit", "cdadt"]},
  {name: "jhfdmw", weight: 20},
  {name: "ngftkym", weight: 74},
  {name: "vjfzfkf", weight: 69},
  {name: "odhnwli", weight: 41},
  {name: "popwmey", weight: 1793,
    children: ["ncsro", "lwcbxxt", "apzzew"]},
  {name: "mjeni", weight: 85},
  {name: "perxaan", weight: 29},
  {name: "edxsfa", weight: 85,
    children: ["grxfsjm", "uwwmhl", "ddjoygw"]},
  {name: "oknhrfd", weight: 30},
  {name: "kbbgkmr", weight: 2136,
    children: ["occdw", "hawmox", "uzjpp"]},
  {name: "nvglnd", weight: 29},
  {name: "dviuy", weight: 186,
    children: ["puyxatg", "piztdav"]},
  {name: "baesgig", weight: 67},
  {name: "qcylfon", weight: 93},
  {name: "wmhucb", weight: 72},
  {name: "xlpgtmn", weight: 31},
  {name: "wgqus", weight: 41},
  {name: "rqxgeqm", weight: 72},
  {name: "cdcwgnc", weight: 189,
    children: ["xzfggf", "gebon"]},
  {name: "grnafmr", weight: 956,
    children: ["jmhafl", "juukhpw", "znitfpo"]},
  {name: "yoddspj", weight: 66},
  {name: "zvkpq", weight: 83,
    children: ["apsinu", "vwgvrw"]},
  {name: "kcqlos", weight: 84,
    children: ["wtfhx", "wdanz", "loksq", "qnwlb", "ojqkqas"]},
  {name: "ueusbib", weight: 231,
    children: ["taewvbl", "xhrgl"]},
  {name: "agyir", weight: 409,
    children: ["mjxqlx", "vnpjttm", "mlhqqjt"]},
  {name: "aqrawj", weight: 158,
    children: ["yjuzr", "gfnhg", "ibxkkj", "pealhre"]},
  {name: "blqvp", weight: 18},
  {name: "kaylk", weight: 12619,
    children: ["wymbxxi", "kumyda", "beesdrz", "dfrdid"]},
  {name: "pgyabg", weight: 29},
  {name: "tamkjw", weight: 61},
  {name: "lkjbvw", weight: 847,
    children: ["gykhcku", "piaeb", "yxdkhlx"]},
  {name: "bcicoat", weight: 131,
    children: ["sgabt", "gjmaeb"]},
  {name: "uulxzg", weight: 9},
  {name: "onnfacs", weight: 63612,
    children: ["ftaxy", "nrkctj", "tfnsk"]},
  {name: "hepedt", weight: 45},
  {name: "gebon", weight: 51},
  {name: "rtoecx", weight: 45},
  {name: "hfqgoz", weight: 20},
  {name: "taewvbl", weight: 30},
  {name: "hhsge", weight: 55},
  {name: "immxnu", weight: 23},
  {name: "mkrkkri", weight: 21},
  {name: "tfxzu", weight: 13},
  {name: "netxsyl", weight: 93},
  {name: "tyvztv", weight: 22},
  {name: "xzfbr", weight: 82},
  {name: "gastvq", weight: 2076,
    children: ["boyyulo", "dbics", "vsshf"]},
  {name: "slvygt", weight: 81},
  {name: "wixxqy", weight: 59},
  {name: "cddgm", weight: 149,
    children: ["ahgtamk", "ortqko"]},
  {name: "scjjqzv", weight: 2105,
    children: ["rzkgb", "sahdqia"]},
  {name: "amfdzum", weight: 122,
    children: ["ivfbcy", "slifb"]},
  {name: "ntftdmt", weight: 49},
  {name: "wiqohmb", weight: 26},
  {name: "vbnobqv", weight: 76},
  {name: "xuoags", weight: 86},
  {name: "uzaousy", weight: 98,
    children: ["muahqz", "shojrc"]},
  {name: "gjmaeb", weight: 9},
  {name: "nhxtvr", weight: 35},
  {name: "jscpi", weight: 26},
  {name: "ofjopcm", weight: 94},
  {name: "bkpzlxc", weight: 63},
  {name: "omoin", weight: 76},
  {name: "roquwk", weight: 30},
  {name: "xwyzhc", weight: 19},
  {name: "mdtrudc", weight: 76},
  {name: "pjrtq", weight: 47},
  {name: "fcxdhb", weight: 59},
  {name: "qigwdd", weight: 70},
  {name: "ajzenm", weight: 249,
    children: ["spcwbv", "eixgei"]},
  {name: "kcqshd", weight: 31},
  {name: "oyjrsw", weight: 161,
    children: ["lxqing", "omiwktf"]},
  {name: "iflde", weight: 189,
    children: ["xlkuot", "kwvkbv", "nhxtvr", "qryupbf"]},
  {name: "gjnnotg", weight: 23},
  {name: "xzawv", weight: 55},
  {name: "quaey", weight: 85},
  {name: "jakdiea", weight: 74,
    children: ["yylhcwe", "lxxfs", "fzjuimt", "sjqnci", "nqvntc"]},
  {name: "frqzl", weight: 99},
  {name: "isrgun", weight: 270,
    children: ["nhqgb", "byegnb"]},
  {name: "mabydz", weight: 78},
  {name: "dbpxdxl", weight: 26},
  {name: "tvooztp", weight: 93},
  {name: "mpamey", weight: 19},
  {name: "srxvc", weight: 27},
  {name: "tflkhk", weight: 5},
  {name: "vrkihvw", weight: 7,
    children: ["arqruaa", "vbnobqv", "zzufnfx"]},
  {name: "rlxnjv", weight: 13},
  {name: "wbtniv", weight: 12},
  {name: "uwnvz", weight: 66},
  {name: "ouabu", weight: 95,
    children: ["skhjuz", "yjpmbe", "nvaiuzb"]},
  {name: "hzcbok", weight: 12},
  {name: "oqfan", weight: 123,
    children: ["umrrz", "ozhoji"]},
  {name: "hejkytc", weight: 89},
  {name: "waukis", weight: 18},
  {name: "imzuug", weight: 26},
  {name: "lmmde", weight: 76},
  {name: "uzjpp", weight: 156,
    children: ["ysqronq", "zmnaori"]},
  {name: "isrqnr", weight: 68},
  {name: "bpopmlv", weight: 264,
    children: ["lshtqgp", "vrezr"]},
  {name: "hznqtl", weight: 41},
  {name: "vfipmtl", weight: 88},
  {name: "kqlwcz", weight: 45},
  {name: "kjzvcr", weight: 69},
  {name: "hoemev", weight: 39},
  {name: "eepyf", weight: 42},
  {name: "qhfpnc", weight: 244,
    children: ["elqusuf", "jjukrje"]},
  {name: "aisrfn", weight: 80},
  {name: "duyvc", weight: 47,
    children: ["amydoj", "pwzlax", "wiuxjsd", "tfkrv", "gbiqrgk"]},
  {name: "wflwje", weight: 38},
  {name: "ykxkahj", weight: 39},
  {name: "fovzx", weight: 55},
  {name: "okard", weight: 89},
  {name: "izmwsib", weight: 89},
  {name: "iymnx", weight: 174,
    children: ["azdiwj", "gqejmuy", "kxrorv"]},
  {name: "lpycpao", weight: 93},
  {name: "hkljrrq", weight: 5},
  {name: "xxnqt", weight: 139,
    children: ["dhpxdx", "zvkpq", "kajmeo", "dzxzka"]},
  {name: "xtmjhz", weight: 14},
  {name: "stwrufp", weight: 84,
    children: ["qtdha", "isaicgr", "dhilxlz", "gadpuyh"]},
  {name: "mpnqbac", weight: 71},
  {name: "ludvj", weight: 172,
    children: ["nsoes", "vxlbjn"]},
  {name: "pctuggx", weight: 58},
  {name: "xhjfj", weight: 8},
  {name: "dbuzcp", weight: 29},
  {name: "edgaqnw", weight: 80},
  {name: "istew", weight: 69},
  {name: "waaostj", weight: 63,
    children: ["hxexq", "ylwwnxo"]},
  {name: "prewuzd", weight: 50},
  {name: "vmghntr", weight: 1313,
    children: ["jzmhc", "oqfan", "cfcqxkp", "midyfh"]},
  {name: "nrvgs", weight: 189,
    children: ["ryqaxd", "owjjchv"]},
  {name: "jtnoixl", weight: 40},
  {name: "mhrsu", weight: 97},
  {name: "wvlri", weight: 55,
    children: ["smhbvd", "lnpla", "deuwm"]},
  {name: "cyfuqq", weight: 222},
  {name: "furgqht", weight: 93},
  {name: "euask", weight: 26,
    children: ["datez", "csrjic", "puuiqr", "wfwfpat"]},
  {name: "ikkxpuo", weight: 83},
  {name: "dnigru", weight: 52,
    children: ["pmyvcx", "fmtmlgd"]},
  {name: "ufaxhkb", weight: 46,
    children: ["fluqhsw", "vbiwa", "woasw"]},
  {name: "ajrle", weight: 75},
  {name: "lplefi", weight: 65},
  {name: "eemyrwb", weight: 346,
    children: ["tayge", "qdoiidp", "kilai"]},
  {name: "jpzmpas", weight: 235,
    children: ["kfjztke", "idfhr"]},
  {name: "dgwfi", weight: 47},
  {name: "lrqffb", weight: 65},
  {name: "isaicgr", weight: 85},
  {name: "uxsrdpn", weight: 1843,
    children: ["qjtan", "eihea", "nlknxtv", "pclpjq", "pvzri", "fxgehjm", "dzjvx"]},
  {name: "loksq", weight: 293,
    children: ["fpejk", "qxmdjq", "ragqe", "acfzx"]},
  {name: "ynrpdhv", weight: 219,
    children: ["cbrfntx", "raqfhc"]},
  {name: "mhnprqw", weight: 97},
  {name: "vuatju", weight: 52},
  {name: "bxvaxw", weight: 60},
  {name: "awmjc", weight: 45},
  {name: "vdkjcp", weight: 56,
    children: ["azfrf", "gdkka"]},
  {name: "knofme", weight: 7,
    children: ["ipgoewc", "pjprk", "uqyqwny"]},
  {name: "atcrc", weight: 20},
  {name: "szyya", weight: 149,
    children: ["mdgqhkw", "hgignr"]},
  {name: "lhclwhi", weight: 29},
  {name: "ktwba", weight: 94},
  {name: "tgedm", weight: 91},
  {name: "gklao", weight: 150,
    children: ["zdmgb", "ncdbvaa"]},
  {name: "cwcmr", weight: 857,
    children: ["iudquk", "dnwlq", "efriw"]},
  {name: "djfzb", weight: 12},
  {name: "kuiik", weight: 72},
  {name: "umrrz", weight: 70},
  {name: "jgfgg", weight: 5,
    children: ["edzfey", "tvbizrm"]},
  {name: "ortfml", weight: 150,
    children: ["arvmgnd", "gwhqhzb"]},
  {name: "qzwkx", weight: 73},
  {name: "bzxcjoz", weight: 80},
  {name: "eblyrp", weight: 381,
    children: ["dbpxdxl", "imzuug"]},
  {name: "sbkqck", weight: 329,
    children: ["kycvcdb", "ufknphd"]},
  {name: "bskvox", weight: 68},
  {name: "ygjhtt", weight: 21},
  {name: "synxk", weight: 60},
  {name: "nvaiuzb", weight: 80},
  {name: "ehvljub", weight: 97,
    children: ["vjikgc", "nfebqt"]},
  {name: "ygnys", weight: 57},
  {name: "lgaruuy", weight: 96,
    children: ["dwxem", "rzqdqj"]},
  {name: "eesynky", weight: 858,
    children: ["vzgukn", "dyvizny", "cjvfvb", "tkhlk", "bucnil", "atkes"]},
  {name: "huqgqdb", weight: 63,
    children: ["hdxbz", "wxsok", "ayntidu", "bnhfx"]},
  {name: "pfolrs", weight: 25},
  {name: "fltpoim", weight: 86},
  {name: "ehpmmve", weight: 49},
  {name: "bwiee", weight: 72},
  {name: "bfkcjn", weight: 59},
  {name: "hyukvw", weight: 79,
    children: ["hhgop", "cnrznxh", "gdnzlar", "xzmax"]},
  {name: "xmwcvfq", weight: 95,
    children: ["iscthbd", "ontvyu", "bpmqk", "hkorax"]},
  {name: "bruxjz", weight: 33},
  {name: "rvshkx", weight: 9},
  {name: "auoba", weight: 233,
    children: ["hjeeb", "clgsp"]},
  {name: "abuszt", weight: 195,
    children: ["avugbx", "rwupp", "mjvpc"]},
  {name: "aagrt", weight: 35,
    children: ["isrqnr", "fvvrow", "fuzizpc"]},
  {name: "zwprtx", weight: 5},
  {name: "vzgukn", weight: 279,
    children: ["fcxdhb", "xxswx"]},
  {name: "wbxcy", weight: 27},
  {name: "njoqwl", weight: 12},
  {name: "rgnjr", weight: 47},
  {name: "ejkioj", weight: 25},
  {name: "yatllw", weight: 107,
    children: ["palczfm", "jgxph"]},
  {name: "ibokijo", weight: 145,
    children: ["vbutj", "hpcncb"]},
  {name: "qopbuhe", weight: 33},
  {name: "rkujtq", weight: 7},
  {name: "qizgiau", weight: 275},
  {name: "ysuoctn", weight: 88},
  {name: "ntmldq", weight: 301,
    children: ["ocsqis", "xtmjhz"]},
  {name: "sahdqia", weight: 19},
  {name: "hviil", weight: 3327,
    children: ["xvafyvk", "jqjzfu", "scjjqzv"]},
  {name: "boncwia", weight: 42},
  {name: "xvcxtx", weight: 20},
  {name: "tshqhis", weight: 97},
  {name: "rlvfcl", weight: 357},
  {name: "fzzbt", weight: 9659,
    children: ["sddaxt", "xkdjnv", "axarhk"]},
  {name: "yeqsa", weight: 66},
  {name: "xxlzsza", weight: 76},
  {name: "fzqhw", weight: 33},
  {name: "xefpxn", weight: 95,
    children: ["cqoyqhn", "txkyw"]},
  {name: "xcrvb", weight: 42},
  {name: "xwpuhf", weight: 98,
    children: ["tzepblp", "slttwe"]},
  {name: "qryupbf", weight: 35},
  {name: "ryahia", weight: 361,
    children: ["mqkaob", "anbdqml", "aqkdmt"]},
  {name: "apsinu", weight: 59},
  {name: "nqmede", weight: 101,
    children: ["xbmbzn", "mypzbk"]},
  {name: "gexwzw", weight: 277,
    children: ["ehvljub", "abuszt", "vfkzaix", "ghzsq"]},
  {name: "owagdf", weight: 52},
  {name: "cekovn", weight: 21},
  {name: "jqjzfu", weight: 283,
    children: ["qcvigx", "ojxixj", "yjvyqo", "kvoeo", "dmufjvd", "ufaxhkb"]},
  {name: "clxdcd", weight: 50,
    children: ["srnuyz", "aulrhvv", "oofhjqx", "ofjopcm"]},
  {name: "nshqf", weight: 76},
  {name: "ljzqzlt", weight: 26},
  {name: "gopynr", weight: 95,
    children: ["boncwia", "ugoyb", "pawxyqe"]},
  {name: "mcwevy", weight: 1085,
    children: ["cubeivy", "ejkfjsb", "wlffbug"]},
  {name: "jghceu", weight: 39},
  {name: "cigtx", weight: 286,
    children: ["cshmi", "uytekqt", "bhwirm"]},
  {name: "jxdpzr", weight: 208},
  {name: "kxlbaue", weight: 126,
    children: ["vkugys", "gkgxg"]},
  {name: "kxrorv", weight: 43},
  {name: "dzkqrjf", weight: 38},
  {name: "mgrolho", weight: 54},
  {name: "kvwjces", weight: 23},
  {name: "grdozg", weight: 37},
  {name: "hygnrpp", weight: 64},
  {name: "shojrc", weight: 65},
  {name: "qleml", weight: 59},
  {name: "hjjchx", weight: 58},
  {name: "uicmcph", weight: 8},
  {name: "coiuo", weight: 174,
    children: ["tplrfil", "nxnegu"]},
  {name: "lccfqhm", weight: 173,
    children: ["ivejr", "mabydz"]},
  {name: "udyms", weight: 1120,
    children: ["lsmylfm", "bzwof", "xmwcvfq"]},
  {name: "taljv", weight: 79,
    children: ["ploofc", "xzbry"]},
  {name: "ybsetv", weight: 55},
  {name: "qxmdjq", weight: 10},
  {name: "nlnwd", weight: 12},
  {name: "xzfggf", weight: 51},
  {name: "qxylp", weight: 169,
    children: ["dujat", "wonqggh"]},
  {name: "ekild", weight: 72},
  {name: "cidfe", weight: 8},
  {name: "pzbruav", weight: 66},
  {name: "wnsnr", weight: 1086,
    children: ["chmmaa", "zcvlo", "lktenr"]},
  {name: "qcgirq", weight: 99},
  {name: "kcftmnv", weight: 23},
  {name: "mpunhg", weight: 12},
  {name: "bhwirm", weight: 14},
  {name: "wztqxw", weight: 47},
  {name: "jzkkmio", weight: 61},
  {name: "anxrcns", weight: 19},
  {name: "rddasm", weight: 90},
  {name: "gomgkol", weight: 1877,
    children: ["nqmede", "vtrhhwq", "tiseyn"]},
  {name: "treywsr", weight: 11},
  {name: "zyghjdm", weight: 168,
    children: ["bbehb", "zazwgl"]},
  {name: "fantkyj", weight: 1356,
    children: ["tyviul", "sbkqck", "karmp"]},
  {name: "puyxatg", weight: 6},
  {name: "mbzah", weight: 35,
    children: ["mfcryoc", "nnjtb"]},
  {name: "bjdzogu", weight: 145,
    children: ["vkcixm", "jsjxl"]},
  {name: "qxzeexk", weight: 182,
    children: ["hfqgoz", "dwsljog", "jhfdmw", "mzxyyfo"]},
  {name: "orsmk", weight: 52},
  {name: "wdcathn", weight: 68},
  {name: "nfbln", weight: 70},
  {name: "hnevf", weight: 7},
  {name: "iiwvkl", weight: 291},
  {name: "bbehb", weight: 30},
  {name: "tvbizrm", weight: 84},
  {name: "abjmnp", weight: 84},
  {name: "cairgd", weight: 22},
  {name: "nnjtb", weight: 57},
  {name: "ucyuje", weight: 205,
    children: ["kampbl", "lplefi"]},
  {name: "pjprk", weight: 58},
  {name: "aulrhvv", weight: 94},
  {name: "pealhre", weight: 45},
  {name: "xbomtaj", weight: 84},
  {name: "nqmrbb", weight: 20},
  {name: "vxgsa", weight: 37,
    children: ["uwnvz", "dzone", "yoddspj", "erxep"]},
  {name: "afwufw", weight: 410,
    children: ["lyhuihb", "wvihp"]},
  {name: "iyywca", weight: 20},
  {name: "ejwrem", weight: 452,
    children: ["pipax", "jxdpzr", "lpilno"]},
  {name: "guwoota", weight: 144,
    children: ["kpyped", "vtxpy", "immxnu"]},
  {name: "dyvizny", weight: 317,
    children: ["yrpolf", "hjgaun"]},
  {name: "ploofc", weight: 52},
  {name: "bukih", weight: 82,
    children: ["ebargy", "netxsyl", "qcylfon", "furgqht"]},
  {name: "ilstw", weight: 97},
  {name: "sszjzj", weight: 205},
  {name: "aqkdmt", weight: 31},
  {name: "koqxg", weight: 55,
    children: ["bxlur", "ebjym"]},
  {name: "nrkctj", weight: 4287,
    children: ["xxnqt", "dpiexx", "hkgcdih", "lrslve"]},
  {name: "okmrsd", weight: 21,
    children: ["gcsiaut", "ppakqms", "odhnwli", "dyvgigf"]},
  {name: "crkcm", weight: 80},
  {name: "ycxsmt", weight: 167,
    children: ["snxzn", "abhtg"]},
  {name: "fmfksfr", weight: 57},
  {name: "oofhjqx", weight: 94},
  {name: "apzzew", weight: 77,
    children: ["xeqle", "fovzx"]},
  {name: "pbmhfx", weight: 51,
    children: ["ffncznl", "nyojm", "rfhbuox", "rsjswd", "ntmldq", "iflde", "ythhfq"]},
  {name: "jnvrw", weight: 159,
    children: ["njmxjzn", "aqzibdb"]},
  {name: "zqkhpn", weight: 5},
  {name: "wfwfpat", weight: 58},
  {name: "bilbca", weight: 89},
  {name: "osbaf", weight: 63},
  {name: "wqqmvoe", weight: 76},
  {name: "oyhgs", weight: 93},
  {name: "wpirdu", weight: 80,
    children: ["wcdlx", "jbqfn", "xbomtaj"]},
  {name: "bnhfx", weight: 753,
    children: ["gvfit", "jgfgg", "daebu", "jwmtw", "qhttqrn", "ibokijo"]},
  {name: "zuvar", weight: 45},
  {name: "ldcdes", weight: 51},
  {name: "puuiqr", weight: 58},
  {name: "vegnaz", weight: 3528,
    children: ["upksf", "lzife", "jwioxco", "trvqvd"]},
  {name: "amliqh", weight: 47},
  {name: "pkvblpt", weight: 91},
  {name: "crtmtt", weight: 81},
  {name: "oahdsnf", weight: 241,
    children: ["tetsf", "zmekfc"]},
  {name: "fjjgfl", weight: 188,
    children: ["waturpr", "fedmbom", "ieebgv"]},
  {name: "rhfcxzg", weight: 79},
  {name: "kjegcl", weight: 87,
    children: ["xwyzhc", "dxmuy", "wgcckll"]},
  {name: "rxxft", weight: 393,
    children: ["jwytokt", "xiecr"]},
  {name: "usudfnb", weight: 48},
  {name: "vtrhhwq", weight: 159},
  {name: "hawmox", weight: 30,
    children: ["mdubrq", "puwktt", "istew", "vjfzfkf"]},
  {name: "cshmi", weight: 14},
  {name: "vtkaia", weight: 37},
  {name: "yiqqluf", weight: 200,
    children: ["ddhzzxi", "qnknn"]},
  {name: "rfhbuox", weight: 185,
    children: ["wkyhcm", "jydmmzj"]},
  {name: "hbvroo", weight: 60,
    children: ["hejkytc", "uiqwd"]},
  {name: "jlick", weight: 240,
    children: ["vuatju", "cqfebqe"]},
  {name: "sunnnk", weight: 38},
  {name: "umdid", weight: 49},
  {name: "qcvigx", weight: 152,
    children: ["rhfcxzg", "gqauurp"]},
  {name: "keyfi", weight: 37},
  {name: "axilhr", weight: 41,
    children: ["yblpan", "qigwdd"]},
  {name: "tuwix", weight: 82,
    children: ["kucajqv", "ymednx", "bgkxjiw"]},
  {name: "yrmjwj", weight: 29},
  {name: "claeea", weight: 84},
  {name: "yrahjwp", weight: 104,
    children: ["qllpxw", "euhgp"]},
  {name: "qdoiidp", weight: 180},
  {name: "hdxbz", weight: 31,
    children: ["yrwzi", "isrgun", "luzyhbe", "goaeny"]},
  {name: "ctaya", weight: 426},
  {name: "sddaxt", weight: 2232,
    children: ["mqtmr", "lqtckpk"]},
  {name: "yhfjs", weight: 38},
  {name: "xysxg", weight: 62},
  {name: "ahvzxw", weight: 11},
  {name: "tnpiig", weight: 97},
  {name: "hyvzyy", weight: 18},
  {name: "wckuhkd", weight: 15},
  {name: "lgmfk", weight: 72},
  {name: "wfinqez", weight: 63},
  {name: "efrqc", weight: 1019,
    children: ["skhjb", "peqsua", "aijgw", "zzzcrp"]},
  {name: "wvwqp", weight: 91,
    children: ["mkbny", "oukxnyz", "qeidnw", "jlick", "jauxs", "ebtazb", "ceghgg"]},
  {name: "dzlygu", weight: 229,
    children: ["zmrjb", "abvvbtl"]},
  {name: "rtydk", weight: 2202,
    children: ["wlxkzyu", "ikmldw", "guwoota", "iczndtj"]},
  {name: "prsysf", weight: 318,
    children: ["bnrgfa", "pvtmulz", "koviipt", "qtfpf"]},
  {name: "bjdfo", weight: 10},
  {name: "qavye", weight: 22},
  {name: "phxjq", weight: 75},
  {name: "ujmboh", weight: 42},
  {name: "mrexh", weight: 68,
    children: ["aagrt", "klnuy", "atcckfh"]},
  {name: "dxspx", weight: 7},
  {name: "boyyulo", weight: 67,
    children: ["vtkaia", "tufamsz"]},
  {name: "lrslve", weight: 403,
    children: ["dnigru", "ylftgo", "byijdr"]},
  {name: "dzone", weight: 66},
  {name: "qjdum", weight: 88},
  {name: "rzkgb", weight: 19},
  {name: "lrriax", weight: 89},
  {name: "mypzbk", weight: 29},
  {name: "vnpjttm", weight: 15},
  {name: "feogbnr", weight: 25},
  {name: "euhgp", weight: 19},
  {name: "dujat", weight: 7},
  {name: "jncdjr", weight: 6},
  {name: "fedjn", weight: 76},
  {name: "ydnxkn", weight: 34,
    children: ["zkpbt", "tnvtn"]},
  {name: "vkcixm", weight: 78},
  {name: "xcubkli", weight: 41},
  {name: "daebu", weight: 41,
    children: ["zlrwizb", "rcelntk"]},
  {name: "emhikp", weight: 20},
  {name: "jydmmzj", weight: 72},
  {name: "yrpolf", weight: 40},
  {name: "temdg", weight: 73},
  {name: "chpcn", weight: 28,
    children: ["fgctru", "uiaqaai", "qxzeexk", "isdcga"]},
  {name: "gnirnf", weight: 5},
  {name: "ffncznl", weight: 315,
    children: ["jhxdgxv", "iilaoq"]},
  {name: "klfkq", weight: 31},
  {name: "ierxej", weight: 205},
  {name: "bstmzd", weight: 96,
    children: ["kgwuliy", "pohtiuv", "qxoljws", "amliqh"]},
  {name: "xxswx", weight: 59},
  {name: "azdiwj", weight: 43},
  {name: "ceghgg", weight: 287,
    children: ["urgiwa", "dkhyk", "awwicqq"]},
  {name: "jgtled", weight: 95},
  {name: "vtzpyp", weight: 55},
  {name: "adrate", weight: 75,
    children: ["hfyevuq", "nyfzqsd"]},
  {name: "elsqz", weight: 253,
    children: ["rnkrh", "obfxoch"]},
  {name: "mkxke", weight: 74,
    children: ["uhcrfl", "bnhfnlw", "hdzls", "pcfilur", "onnfacs", "wdugfj", "jakdiea"]},
  {name: "msutjz", weight: 20},
  {name: "osevo", weight: 61,
    children: ["crkcm", "bzxcjoz", "qrlcg"]},
  {name: "rfldln", weight: 53,
    children: ["vwepws", "rdzzlw", "xfnmqd", "ugmwpnx"]},
  {name: "glcrysh", weight: 78},
  {name: "izgqj", weight: 38},
  {name: "azkwjyi", weight: 34,
    children: ["fgdbbei", "enuqt"]},
  {name: "kemaenc", weight: 31},
  {name: "dzwgtf", weight: 68},
  {name: "ruadem", weight: 1126,
    children: ["osevo", "bjdzogu", "ablbrw"]},
  {name: "pduav", weight: 264,
    children: ["mdsms", "edgaqnw"]},
  {name: "cqcbbbr", weight: 46},
  {name: "yoyvf", weight: 131},
  {name: "zntwpqo", weight: 10},
  {name: "xozkvy", weight: 19},
  {name: "kvoeo", weight: 202,
    children: ["mgrolho", "vhyyv"]},
  {name: "iqtij", weight: 72},
  {name: "tbimd", weight: 59,
    children: ["hvtqmrn", "oscxinx", "oubxwbc", "fzugjg"]},
  {name: "owjjchv", weight: 23},
  {name: "enjrxrw", weight: 219,
    children: ["pgyabg", "nvglnd", "itnpmen", "yrmjwj"]},
  {name: "xfcoi", weight: 23,
    children: ["ykpcq", "dqggh", "fitaq", "rxxft", "jkmzstd", "xiuxqpp", "qvdkqw"]},
  {name: "satjbta", weight: 241,
    children: ["jzzng", "kirybeg"]},
  {name: "hgnkw", weight: 9,
    children: ["osbaf", "wfinqez", "oksum"]},
  {name: "mqtksj", weight: 281,
    children: ["nrneucv", "zqkhpn"]},
  {name: "ghzsq", weight: 97,
    children: ["pzpwzpp", "lmdteh"]},
  {name: "muiela", weight: 120,
    children: ["jrqht", "eepyf", "njqjd"]},
  {name: "xhkbihe", weight: 169},
  {name: "biqeev", weight: 68},
  {name: "mjxqlx", weight: 15},
  {name: "vjikgc", weight: 61},
  {name: "ncsro", weight: 109,
    children: ["cpdapys", "niphm"]},
  {name: "eadol", weight: 72},
  {name: "ywshnoc", weight: 19},
  {name: "appwc", weight: 74,
    children: ["eyqpybt", "unwpat", "cmpldn"]},
  {name: "vkbpp", weight: 23},
  {name: "nlknxtv", weight: 9,
    children: ["qweyg", "nbidkx"]},
  {name: "kdnrfhs", weight: 454},
  {name: "ppakqms", weight: 41},
  {name: "wiuxjsd", weight: 249,
    children: ["rgdsxy", "mpunhg"]},
  {name: "owzsiku", weight: 52,
    children: ["zvhjz", "oyhgs"]},
  {name: "jlzlxib", weight: 48},
  {name: "qyrope", weight: 62,
    children: ["yrucl", "ldxqsu", "oihlb", "eblyrp"]},
  {name: "nqobvf", weight: 66},
  {name: "rjzmzv", weight: 72},
  {name: "hizhauj", weight: 72},
  {name: "utydsr", weight: 37},
  {name: "mdwrg", weight: 122,
    children: ["hutkx", "hbdsnvx", "xtgrt", "fzqhw"]},
  {name: "dxmuy", weight: 19},
  {name: "dugorw", weight: 80},
  {name: "jjqpm", weight: 23},
  {name: "ninnxgi", weight: 258},
  {name: "nqgfa", weight: 24},
  {name: "zpzdnz", weight: 62},
  {name: "juflvu", weight: 85,
    children: ["rnrxeb", "wbmahc", "tmzut"]},
  {name: "cqhgy", weight: 48},
  {name: "xezjpye", weight: 862,
    children: ["bswzafr", "pdumcu", "vdppt"]},
  {name: "lrvwrl", weight: 85},
  {name: "cdlqgyh", weight: 291},
  {name: "hyhvgle", weight: 19},
  {name: "wzzey", weight: 54},
  {name: "hhgop", weight: 49},
  {name: "rdcew", weight: 31},
  {name: "rxoja", weight: 18},
  {name: "dlmmqrm", weight: 41},
  {name: "kvmxfku", weight: 54},
  {name: "ayqsng", weight: 18},
  {name: "niphm", weight: 39},
  {name: "nxrhbhh", weight: 87,
    children: ["lmvbhm", "orwwh"]},
  {name: "fpejk", weight: 10},
  {name: "sfvfge", weight: 292,
    children: ["kvrmjma", "rvshkx"]},
  {name: "gdkka", weight: 44},
  {name: "smhbvd", weight: 263,
    children: ["qalkey", "rkujtq"]},
  {name: "ieebgv", weight: 85,
    children: ["jcortpe", "fslbtk"]},
  {name: "clnzh", weight: 254},
  {name: "fluqhsw", weight: 88},
  {name: "igwetl", weight: 68},
  {name: "dhnttwg", weight: 72},
  {name: "gcsiaut", weight: 41},
  {name: "hgignr", weight: 56},
  {name: "yywuo", weight: 21},
  {name: "pzgagh", weight: 17},
  {name: "cnrznxh", weight: 49},
  {name: "cgyxd", weight: 84},
  {name: "yheme", weight: 192,
    children: ["isvfqpy", "qopbuhe"]},
  {name: "iftzv", weight: 258},
  {name: "wknjhvo", weight: 107,
    children: ["swwwls", "earhrts", "ogfsdjs"]},
  {name: "cbwagy", weight: 89},
  {name: "zdmgb", weight: 54},
  {name: "chozum", weight: 24},
  {name: "yqndxmd", weight: 43},
  {name: "vwgvrw", weight: 59},
  {name: "mnezur", weight: 84},
  {name: "kajmeo", weight: 115,
    children: ["yqndxmd", "mxnvqf"]},
  {name: "ftquc", weight: 84,
    children: ["grctgck", "igoifku", "xefpxn", "cddgm"]},
  {name: "rcvhb", weight: 10,
    children: ["lvbgz", "utyriu", "zpzdnz", "wjuyj"]},
  {name: "ghpotnp", weight: 181,
    children: ["vdjoaq", "xvcxtx"]},
  {name: "tefpuyj", weight: 90,
    children: ["dbirye", "cfegyp"]},
  {name: "exryas", weight: 72},
  {name: "ixxaaz", weight: 88,
    children: ["wckuhkd", "hjqlg"]},
  {name: "dtjmr", weight: 61},
  {name: "jhhnkho", weight: 48},
  {name: "tfnsk", weight: 7354,
    children: ["otxmmd", "vrkihvw", "nndiv"]},
  {name: "idfhr", weight: 28},
  {name: "dssoru", weight: 95},
  {name: "piaeb", weight: 99},
  {name: "cfcmep", weight: 51,
    children: ["dsdvxuw", "bqxiezq", "bqypkb"]},
  {name: "dmufjvd", weight: 310},
  {name: "bbenpz", weight: 43},
  {name: "jwdtam", weight: 93},
  {name: "ehajus", weight: 63},
  {name: "unxjpl", weight: 91},
  {name: "xogbq", weight: 19,
    children: ["igwetl", "dzwgtf", "wdcathn", "bskvox"]},
  {name: "njqjd", weight: 42},
  {name: "hpxoxk", weight: 57},
  {name: "nlnqo", weight: 92},
  {name: "kdjoii", weight: 83},
  {name: "xhrgl", weight: 30},
  {name: "cjvfvb", weight: 301,
    children: ["zfbolo", "fvord", "tiqmony", "snqeb"]},
  {name: "glbnsvc", weight: 17},
  {name: "huantpz", weight: 186,
    children: ["oxdqy", "mpnqbac"]},
  {name: "lktenr", weight: 135,
    children: ["meonp", "ampno"]},
  {name: "cqhnl", weight: 53},
  {name: "cidce", weight: 454},
  {name: "vcqgruj", weight: 218},
  {name: "tfkrv", weight: 93,
    children: ["cxocay", "zigchs"]},
  {name: "kgwuliy", weight: 47},
  {name: "baqiy", weight: 75},
  {name: "whurga", weight: 13},
  {name: "eoeiflq", weight: 38},
  {name: "fzugjg", weight: 44},
  {name: "mjvpc", weight: 8},
  {name: "tayge", weight: 104,
    children: ["hyhvgle", "anxrcns", "ywshnoc", "qqxng"]},
  {name: "hgnqq", weight: 45},
  {name: "oacpgj", weight: 95},
  {name: "chpvnf", weight: 75},
  {name: "ovdsrbq", weight: 47},
  {name: "pzgqbxm", weight: 75},
  {name: "sdljelr", weight: 32},
  {name: "rijys", weight: 94},
  {name: "qgiwga", weight: 64,
    children: ["onpzd", "jscpi", "ljzqzlt"]},
  {name: "kucajqv", weight: 75},
  {name: "ntnjsb", weight: 13},
  {name: "zxsxos", weight: 45},
  {name: "bzuiexp", weight: 20},
  {name: "ozhoji", weight: 70},
  {name: "cdmidbh", weight: 388,
    children: ["tyvztv", "flgljqv", "cairgd"]},
  {name: "wmqzq", weight: 41},
  {name: "wtfhx", weight: 159,
    children: ["hsagb", "ndpjdmr"]},
  {name: "kmtyyw", weight: 958,
    children: ["bexoza", "rlvfcl", "ajzenm"]},
  {name: "izqne", weight: 9},
  {name: "iudquk", weight: 37,
    children: ["keyfi", "mrmebqc", "grdozg", "pdfzwaz"]},
  {name: "grctgck", weight: 111,
    children: ["umbwe", "qxwiktp"]},
  {name: "kglxzv", weight: 306,
    children: ["bmjswlz", "hjkfjle"]},
  {name: "ndprukh", weight: 90},
  {name: "dzxzka", weight: 67,
    children: ["rhxhumv", "qxwmd"]},
  {name: "ortqko", weight: 58},
  {name: "jkmzstd", weight: 223,
    children: ["kukri", "lzuon", "nfbln"]},
  {name: "kchwzc", weight: 22},
  {name: "ggmgzhd", weight: 54},
  {name: "umbwe", weight: 77},
  {name: "hhmxdvr", weight: 1584,
    children: ["rurhdvo", "xozkvy"]},
  {name: "yzlzly", weight: 76},
  {name: "wtxinor", weight: 22},
  {name: "cikitqj", weight: 58},
  {name: "dbics", weight: 53,
    children: ["wtxinor", "kyrfsv", "kchwzc", "hrbmwq"]},
  {name: "ldxqsu", weight: 45,
    children: ["qogcdog", "mhnprqw", "tshqhis", "ilstw"]},
  {name: "cqoca", weight: 601,
    children: ["mjmjubw", "knofme", "axilhr"]},
  {name: "ufnve", weight: 210,
    children: ["muivti", "glbnsvc", "ialxayo"]},
  {name: "nvmkhp", weight: 84},
  {name: "lxgjn", weight: 60,
    children: ["tihsmo", "xgefj", "crtmtt"]},
  {name: "irvuv", weight: 92},
  {name: "lrsoyci", weight: 99},
  {name: "ctsvgc", weight: 67},
  {name: "ugoyb", weight: 42},
  {name: "joohyti", weight: 76},
  {name: "ykpcq", weight: 77,
    children: ["eqdoyk", "jwvgc", "lrriax", "hycmwzu"]},
  {name: "dwsljog", weight: 20},
  {name: "srnuyz", weight: 94},
  {name: "bxeum", weight: 76},
  {name: "ibbtm", weight: 28},
  {name: "nifzp", weight: 48},
  {name: "ookaq", weight: 81,
    children: ["wocartl", "baesgig"]},
  {name: "aylev", weight: 63,
    children: ["iefpjj", "mdtrudc", "ywvxjtz"]},
  {name: "obfxoch", weight: 25},
  {name: "pfchj", weight: 27},
  {name: "pzyax", weight: 70},
  {name: "jyjyy", weight: 16},
  {name: "awgqw", weight: 5},
  {name: "tldwabo", weight: 24,
    children: ["jznwy", "hhmxdvr", "grnafmr", "qeebfg", "emkuxtl", "rdwgzr"]},
  {name: "aajfrf", weight: 59},
  {name: "lucdfi", weight: 60},
  {name: "rdwgzr", weight: 788,
    children: ["ehsqyyb", "bivovn", "bvjkr"]},
  {name: "muxuwcv", weight: 68},
  {name: "lzife", weight: 657,
    children: ["mkxbl", "xsodot", "sbwqnh"]},
  {name: "oukjop", weight: 37,
    children: ["hyvfpe", "qcgirq"]},
  {name: "wxsok", weight: 1146,
    children: ["oghwfv", "txwypo", "kylpez"]},
  {name: "ahkztpf", weight: 123,
    children: ["ptfuyxs", "oknhrfd"]},
  {name: "lnmmac", weight: 69},
  {name: "zmrjb", weight: 48},
  {name: "hpcncb", weight: 14},
  {name: "tivuls", weight: 24},
  {name: "zqmmc", weight: 111,
    children: ["flrpj", "ctsvgc"]},
  {name: "vtxpy", weight: 23},
  {name: "ythhfq", weight: 38,
    children: ["tnpiig", "coegpi", "mhrsu"]},
  {name: "waturpr", weight: 16,
    children: ["ikegr", "dtjmr", "blcjl"]},
  {name: "lfjkju", weight: 74,
    children: ["zqmmc", "mwuhto", "sewpop", "durycn", "lpkak", "czvjqk"]},
  {name: "puwktt", weight: 69},
  {name: "czllgn", weight: 15},
  {name: "dbirye", weight: 27},
  {name: "hixroxf", weight: 51},
  {name: "zjbmj", weight: 33},
  {name: "oksum", weight: 63},
  {name: "dfrdid", weight: 73,
    children: ["tuwix", "ptczh", "abphjyv"]},
  {name: "jvmpgso", weight: 171,
    children: ["hyvzyy", "waukis", "uhcach"]},
  {name: "wzcmmr", weight: 75},
  {name: "grxfsjm", weight: 75},
  {name: "sbwqnh", weight: 96,
    children: ["muxuwcv", "vabwqou", "biqeev"]},
  {name: "fedmbom", weight: 93,
    children: ["rsebxf", "aprln"]},
  {name: "qjtan", weight: 29,
    children: ["pxijthu", "eadol"]},
  {name: "ptczh", weight: 172,
    children: ["kqlwcz", "hepedt", "rtoecx"]},
  {name: "uiaqaai", weight: 72,
    children: ["jgtled", "boblgpx"]},
  {name: "srybbkw", weight: 80},
  {name: "cdurt", weight: 55},
  {name: "bnhfnlw", weight: 19497,
    children: ["xqrgxx", "vegnaz", "tldwabo", "ltpwxbx", "xjmhhb", "vmwmulw", "hviil"]},
  {name: "fgdbbei", weight: 94},
  {name: "ablbrw", weight: 265,
    children: ["lxukyz", "rpdslp"]},
  {name: "zkmtesi", weight: 41},
  {name: "gjpgk", weight: 121,
    children: ["kzjfx", "cyxdrb", "aulkaf", "msnicb"]},
  {name: "tiseyn", weight: 67,
    children: ["cqcbbbr", "dxonm"]},
  {name: "dafryf", weight: 249},
  {name: "gafbnc", weight: 94},
  {name: "ojwprv", weight: 33,
    children: ["bmxdb", "kapmsr", "wzzey", "kvmxfku"]},
  {name: "hfyevuq", weight: 93},
  {name: "zzzcrp", weight: 100,
    children: ["dsmuem", "xlpgtmn", "rdcew"]},
  {name: "moqub", weight: 15},
  {name: "hbdsnvx", weight: 33},
  {name: "rexbt", weight: 16},
  {name: "abhtg", weight: 81},
  {name: "iscthbd", weight: 80},
  {name: "gkgxg", weight: 36},
  {name: "wdugfj", weight: 72519,
    children: ["qdqkaw", "xfcoi", "rtydk", "kbbgkmr", "uxsrdpn"]},
  {name: "xizhxs", weight: 18},
  {name: "qvtxsu", weight: 23},
  {name: "nxnegu", weight: 32},
  {name: "lugtnb", weight: 33},
  {name: "jscgykv", weight: 5},
  {name: "jbmclpv", weight: 55},
  {name: "abphjyv", weight: 187,
    children: ["elwic", "wgxlaau"]},
  {name: "uhcach", weight: 18}
];

$('#day7b-ans').html("test");

function findWeight(n){
  for(var i=0; i<tower.length;i++){
    if(n == tower[i].name){
      return tower[i].weight;
    }
  }
}

function findKids(parent){
  for(var i=0; i<tower.length;i++){
    if(parent == tower[i].name){
      if( tower[i].hasOwnProperty('children') ){
        return tower[i].children;
      }
      return tower[i].hasOwnProperty('children');
    }
  }
}

var w = 0;

function sumWeight(branch){
  w += findWeight(branch);
  var kids = findKids(branch);
  if(kids){
    for(var i=0; i<kids.length; i++)
      sumWeight(kids[i]);
  }else{
    return;
  }
}

function getAllWeights(){
  /**
  w=0;
  sumWeight("uhcrfl");
  console.log(w);
  w=0;
  sumWeight("bnhfnlw");
  console.log(w);
  w=0;
  sumWeight("hdzls");
  console.log(w);
  w=0;
  sumWeight("pcfilur");
  console.log(w);
  w=0;
  sumWeight("onnfacs"); // this is the node too high (87798)
  console.log(w); // oonfacs wt is: 63612. The other stacks are (87789). 63612 - 9 = 63603.
  // That's not the answer though, so I need to go up the branch.
  w=0;
  sumWeight("wdugfj");
  console.log(w);
  w=0;
  sumWeight("jakdiea");
  console.log(w);
  
  //Onnfacs kids are: ftaxy, nrkctj, tfnsk
  w=0;
  sumWeight("ftaxy"); //8086
  console.log(w);
  w=0;
  sumWeight("nrkctj"); //8059
  console.log(w);
  w=0;
  sumWeight("tfnsk"); //8059
  console.log(w);
  console.log(8086-8059); //27
  console.log(findWeight("ftaxy"));
  console.log(51-27); // 24 - wrong again
  
  
  //ftaxy kids are: lkjbvw, gexwzw, cqoca, xezjpye, ftquc, gggibf, ferhk
  w=0;
  sumWeight("lkjbvw"); //1144
  console.log(w);
  w=0;
  sumWeight("gexwzw"); // 1153
  console.log(w);
  w=0;
  sumWeight("cqoca"); //1144
  console.log(w);
  w=0;
  sumWeight("xezjpye");
  console.log(w);
  w=0;
  sumWeight("ftquc");
  console.log(w);
  w=0;
  sumWeight("gggibf");
  console.log(w);
  w=0;
  sumWeight("ferhk");
  console.log(w);
  
  //gexwzw kids: ehvljub, abuszt, vfkzaix, ghzsq 
  w=0;
  sumWeight("ehvljub");
  console.log(w);
  w=0;
  sumWeight("abuszt");
  console.log(w);
  w=0;
  sumWeight("vfkzaix");
  console.log(w);
  w=0;
  sumWeight("ghzsq");
  console.log(w); **/
  // These are all 219!! gexwzw is the culprit
  console.log(1153-1144); //9
  console.log(findWeight("gexwzw")); //277
  console.log(277-9); // 268
}

getAllWeights();
//console.log(sumWeight("wdugfj"));